# [Homework 7](https://github.com/hanggrian/IIT-ITM513/blob/assets/assignments/hw7.pdf): Data analysis using NumPy

> The focus of this assignment is Data Science. There are various approaches to Data Science in Python programming. This assignment emphasizes using the NumPy Python library.
>
> You may have to install the Python NumPy package if necessary. You can use the command pip (for Windows) or pip3 (for macOS) to install NumPy. You can also use the command; py -m pip install NumPy

## Problem 1

> (INDEXING AND SLICING ARRAYS) Create an array containing the values 1–15, reshape it into a 3-by-5 array, then use indexing and slicing techniques to perform each of the following operations:
>
> 1.  Select row 2.
> 1.  Select column 4.
> 1.  Select rows 0 and 1.
> 1.  Select columns 2–4.
> 1.  Select the element that is in row 1 and column 4.
> 1.  Select all elements from rows 1 and 2 that are in columns 0, 2 and 4.

- [NumPy](https://numpy.org/) array creation and operation.
- Indexing 2-D array by row and column.
- Styling text with ANSI characters.

### Screenshots

1.  Main interface<br><img src="https://github.com/hanggrian/IIT-ITM513/raw/assets/assignments/hw7/screenshot1.png" width="480">

In [ ]:
%load array_slicing.py

## Problem 2

> For this question, please use the NumPy Python library. Make sure you have installed NumPy, Pandas, SciPy, and Matplotlib Python libraries. Use command pip (for Windows) or pip3 (for MacOS).
>
> Write a program to load a given dataset called `student_grades.csv` into a NumPy array. Then determine the following items:
>
> 1.  Display all data on screen.
> 1.  Determine how many students were in the dataset?
> 1.  Display the number of rows and columns of your numpy array.
> 1.  Display the array data types.
> 1.  Display the following Descriptive Statistics of students’ overall percentage scores:
>     1.  Min score
>     1.  Max score
>     1.  Mean value
>     1.  Median
>     1.  Mode
>     1.  Standard Deviation
>     1.  25% and 75% percentile
> 1.  Determine how many students achieved an A grade, B, C, D and F grades.
> 1.  Create a pie chart based on the above grade achievements (option f).
>
> The following is a sample of Question \#2 program output:
>
> ```
> Display data
> [[ 15. 50. 50. ... 207. 1442. 94.1868 ]
>  [ 15. 50. 50. ... 197. 1322. 86.34879]
>  [ 15. 50. 50. ... 210. 1510. 98.62834]
>  ...
>  [ 15. 50. 50. ... 200. 1374. 89.74526]
>  [ 15. 50. 50. ... 195. 1287. 84.0627 ]
>  [ 15. 50. 50. ... 210. 1490. 97.32201]]
>
> There are 33 students
>
> Display numbers of rows and columns
> (33, 32)
>
> Display data type
> float64
>
> Descriptive Statistics ...
>     Min overall score: 29.65382
>     Max overall score: 99.86936
>     Mean: 87.66996787878789
>     Median: 92.88047
>     Std. Dev.: 15.553686425410683
>     Percentile (25%, 75%): [87.1979 96.73416]
>
> Number of students achieved in each grade category:
> 21 A
> 8 B
> 1 C
> 1 D
> 2 F
> ```
>
> ![](https://github.com/hanggrian/IIT-ITM513/raw/assets/assignments/hw7_1.png)

- Using NumPy array converted from [pandas](https://pandas.pydata.org/) CSV reader.
- Statistics powered by NumPy and [SciPy](https://scipy.org/).
- Showing pie chart with [Matplotlib](https://matplotlib.org/).

### Screenshots

1.  Main interface<br><img src="https://github.com/hanggrian/IIT-ITM513/raw/assets/assignments/hw7/screenshot2_1.png" width="480">
1.  Displaying figures<br><img src="https://github.com/hanggrian/IIT-ITM513/raw/assets/assignments/hw7/screenshot2_2.png" width="640">

In [ ]:
%load student_grading.py

## Learning report

> Using Microsoft Word, write a summary report (not a bullet item) with a minimum of 100 words explaining how you completed your assignment. *Please describe your responses, not just yes/no answers.*

[View report](https://github.com/hanggrian/IIT-ITM513/releases/download/hw7/report.pdf) /
[source](report.md)