# [Homework 7](https://github.com/hendraanggrian/IIT-ITM513/blob/assets/assignments/hw7.pdf)

> The focus of this assignment is Data Science. There are various approaches to Data Science in Python programming. This assignment emphasizes using the NumPy Python library.
>
> You may have to install the Python NumPy package if necessary. You can use the command pip (for Windows) or pip3 (for macOS) to install NumPy. You can also use the command; py -m pip install NumPy

## Problem 1

> (INDEXING AND SLICING ARRAYS) Create an array containing the values 1–15, reshape it into a 3-by-5 array, then use indexing and slicing techniques to perform each of the following operations:
>
> 1. Select row 2.
> 2. Select column 4.
> 3. Select rows 0 and 1.
> 4. Select columns 2–4.
> 5. Select the element that is in row 1 and column 4.
> 6. Select all elements from rows 1 and 2 that are in columns 0, 2 and 4.

- 

### Screenshots

1. 

## Problem 2

> For this question, please use the NumPy Python library. Make sure you have installed NumPy, Pandas, SciPy, and Matplotlib Python libraries. Use command pip (for Windows) or pip3 (for MacOS).
>
> Write a program to load a given dataset called `student_grades.csv` into a NumPy array. Then determine the following items:
>
> 1. Display all data on screen.
> 2. Determine how many students were in the dataset?
> 3. Display the number of rows and columns of your numpy array.
> 4. Display the array data types.
> 5. Display the following Descriptive Statistics of students’ overall percentage scores:
>    1. Min score
>    2. Max score
>    3. Mean value
>    4. Median
>    5. Mode
>    6. Standard Deviation
>    7. 25% and 75% percentile
> 6. Determine how many students achieved an A grade, B, C, D and F grades.
> 7. Create a pie chart based on the above grade achievements (option f).
>
> The following is a sample of Question \#2 program output:
>
> ```
> Display data
> [[ 15. 50. 50. ... 207. 1442. 94.1868 ]
>  [ 15. 50. 50. ... 197. 1322. 86.34879]
>  [ 15. 50. 50. ... 210. 1510. 98.62834]
>  ...
>  [ 15. 50. 50. ... 200. 1374. 89.74526]
>  [ 15. 50. 50. ... 195. 1287. 84.0627 ]
>  [ 15. 50. 50. ... 210. 1490. 97.32201]]
>
> There are 33 students
>
> Display numbers of rows and columns
> (33, 32)
>
> Display data type
> float64
>
> Descriptive Statistics ...
>     Min overall score: 29.65382
>     Max overall score: 99.86936
>     Mean: 87.66996787878789
>     Median: 92.88047
>     Std. Dev.: 15.553686425410683
>     Percentile (25%, 75%): [87.1979 96.73416]
>
> Number of students achieved in each grade category:
> 21 A
> 8 B
> 1 C
> 1 D
> 2 F
> ```
>
> ![](https://github.com/hendraanggrian/IIT-ITM513/raw/assets/assignments/hw7_1.png)

- 

### Screenshots

1. 

## Report Summary

> Using Microsoft Word, write a summary report (not a bullet item) with a minimum of 100 words explaining how you completed your assignment. Please describe your responses, not just yes/no answers.
> 
> 1. Did you successfully get your assignment done? Did it run? Any error? Did you get the correct result? Did you test your program thoroughly?
> 2. How much time did you spend completing your assignment?
> 3. Did you find the assignment easy or challenging for you?
> 4. Did you write the program yourself? Did you get any help from anyone?
> 5. When you encountered obstacles to completing your program, how did you resolve the issues? Did you use Google to get help? Describe how Google was able or not able to assist you?
> 6. What did you learn from doing this assignment?
> 7. Any other information you would like to share with your instructor? Make sure you provide program output on each option.